apiVersion: apps/v1
kind: Deployment
metadata:
  name: celery-worker
  namespace: open-wearables
spec:
  replicas: 2
  selector:
    matchLabels:
      app: celery-worker
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 1
  template:
    metadata:
      labels:
        app: celery-worker
    spec:
      containers:
        - name: celery-worker
          image: ${ACCOUNT_ID}.dkr.ecr.${AWS_REGION}.amazonaws.com/open-wearables/backend:${DEPLOY_TAG}
          imagePullPolicy: Always
          command: ["scripts/start/worker.sh"]
          envFrom:
            - secretRef:
                name: open-wearables
          resources:
            requests:
              cpu: 256m
              memory: 512Mi
            limits:
              cpu: 1000m
              memory: 1Gi
